game_name = "kuhn_poker"
num_iterations = 1000
num_traversals = 50
log_frequency = 1
results_file_base = "../results/kuhn_compositional_"
policy_network_layers=()
advantage_network_layers=()
learning_rate=1e-3
batch_size_advantage=64
batch_size_strategy=64
memory_capacity=1e6
policy_network_train_steps=500
advantage_network_train_steps=50
reinitialize_advantage_networks=False
cat_dims=[2, 3, 2, 2, 2]
input_indices=[0, 1, 2, 3, 4]
functions=["add", "mul", "min", "max"]
n_features=128
depth=3