game_name = "kuhn_poker"
num_iterations = 2000
num_traversals = 1
log_frequency = 1
results_file_base = "../results/kuhn_fil_"
policy_network_layers=(3,)
advantage_network_layers=(3,)
learning_rate=1e-3
batch_size_advantage=64
batch_size_strategy=64
memory_capacity=1e6
policy_network_train_steps=10
advantage_network_train_steps=100
reinitialize_advantage_networks=False
cat_dims = [2, 3, 2, 2, 2]
fil_groups=[[(0, 1, 2, 3, 4), 3]]